[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
seq-macro = "0.3.5"
rustc-hash = "1.1.0"
pathfinding = "4.6.0"
z3 = {version = "0.12.1" }
rand = "0.8.5"

[profile.release]
debug = true
